### ISSUE TITLE
I want to know the version of TensorFlow.

### ISSUE THREAD

**Issue by temps1101** [OMR-Research/tf-end-to-end#10]
I was trying your code on google colab, but when running this code below, it returns an error:
code:
```python
python ctc_predict.py -image Data/Example/000051652-1_2_1.png -model Models/semantic_model.meta -vocabulary Data/vocabulary_semantic.txt
```

error:
```python
Traceback (most recent call last):
  File "ctc_predict.py", line 13, in <module>
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'
```

I think this happens because TensorFlow version of google colab is too new. I want to know the version that you used.

sorry for my terrible English, I'm not really good at it🙂

**Comment by htluandc2** [comment]
You can try with Tensorflow 1.15.2 or Tensorflow 1.x. The current repository is not support with new version of Tensorflow and OpenCV.

**Comment by temps1101** [comment]
thank you for the advice!🙏
