### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

### ISSUE THREAD

**Issue by temps1101** [OMR-Research/tf-end-to-end#9]
I was trying to test ctc_predict.py, but this error comes out:
`AttributeError: module 'TensorFlow' has no attribute 'reset_default_graph'`
I think it's because of the TensorFlow version, so I want to know the version of TensorFlow you are using.

By the way, my TensorFlow's version is 2.2.0rc3

**Comment by calvozaragoza** [comment]
You are using a newer version of TensorFlow. This was designed for TensorFlow 1.12 and, as far as I know, it works for any 1.X version, but not for 2.X.

**Comment by temps1101** [comment]
Thank you for replying my question. It worked when I versioned down my TensorFlow to 1.12😀.
